#!/usr/bin/env python3
"""memory_index -- the auto-memory addressed BY DATE, generated from the same clock the sweep uses.

WHY THIS EXISTS. `MEMORY.md` is compacted by replacing lists of lessons with GREPS -- "08-31 and
earlier: grep `memory/lesson-*2026-08-31*`" -- and `[V]` 2026-09-03 SIX of its eleven such patterns
match ZERO files, because **0 of 705 lesson and feedback files carry a date in their filename** while
every `project*` file does. The index is loaded into every session's context and its date lookups
were dead ends; the knowledge survived only because `docs/LESSONS.md` is the real ledger.

The fix is not to rename 705 files (their `name:` slug is the `[[wikilink]]` key, so a rename breaks
every link that points at them) and not to grep the body (`[V]` 702 of 705 carry a date somewhere in
the text, but a lesson MENTIONING a day is not a lesson written that day -- `2026-09-01` matches 39
files where `modified:` matches 35). It is to publish the date the age ladder already computes.

  - ONE rung per file, PRINTED, so a date resting on mtime is visibly weaker than one from
    frontmatter. `status_census.doc_age` owns the ladder; this module only renders it.
  - REGENERATED by every close, so it cannot drift further than one session -- the same discipline
    as the config catalog that is rewritten every boot and never read back.
  - It QUOTES other files' descriptions, so it carries the doc-scope vocabulary marker: an index
    reprinting someone else's words is not making their claims.

    python tools/docs/memory_index.py [--check]
"""
import argparse
import datetime as _dt
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import status_census as SC  # noqa: E402
from status_grammar import read_text, VOCAB_MARKER_DOC  # noqa: E402

INDEX_NAME = "INDEX_BY_DATE.md"
_DESC = re.compile(r'^description:\s*"?(.*?)"?\s*$', re.M)
NL = chr(10)


def entries(env, rs=None):
    """-> [(date, name, rung, description)] for every memory file, newest date first."""
    rs = rs if rs is not None else SC.read_set(env)
    out = []
    for key, (owner, ap) in rs.items():
        if not key.startswith("memory/") or os.path.basename(key) in ("MEMORY.md", INDEX_NAME):
            continue
        t, rung = SC.doc_age(env, key, rs, want_rung=True)
        day = _dt.datetime.fromtimestamp(t, _dt.timezone.utc).strftime("%Y-%m-%d") if t else "?"
        m = _DESC.search(read_text(ap) or "")
        desc = " ".join((m.group(1) if m else "").split())
        out.append((day, os.path.basename(key)[:-3], rung, desc))
    out.sort(key=lambda e: (e[0], e[1]), reverse=True)
    return out


def render(rows):
    by_day = {}
    for day, name, rung, desc in rows:
        by_day.setdefault(day, []).append((name, rung, desc))
    weak = sum(1 for _, _, r, _ in rows if r == "mtime")
    body = [VOCAB_MARKER_DOC, "",
            "# The auto-memory by date -- GENERATED, do not edit",
            "",
            "Written by `tools/docs/memory_index.py` on every `/documentize` close. Edits are lost.",
            "It exists because `memory/lesson-*.md` filenames carry NO date, so a filename glob for a",
            "day matches nothing; the date below is the one `status_census.doc_age` computes, and the",
            "RUNG it came from is printed beside it -- `mtime` is the weakest and means the file said",
            "nothing about its own age ({} of {} files).".format(weak, len(rows)),
            "",
            "To pull a day: find its heading here, then read the files it names.",
            ""]
    for day in sorted(by_day, reverse=True):
        items = sorted(by_day[day])
        body.append("## {}  ({} file{})".format(day, len(items), "" if len(items) == 1 else "s"))
        body.append("")
        for name, rung, desc in items:
            tail = (" -- " + desc[:220]) if desc else ""
            body.append("- [[{}]]{}{}".format(name, "" if rung != "mtime" else " `(mtime)`", tail))
        body.append("")
    return NL.join(body) + NL


def write(env, rs=None):
    """-> (path, changed). Idempotent: an unchanged index is not rewritten."""
    path = os.path.join(env.memory, INDEX_NAME)
    new = render(entries(env, rs))
    old = read_text(path)
    if old == new:
        return path, False
    io.open(path, "w", encoding="utf-8", newline=NL).write(new)
    return path, True


def stale(env, rs=None):
    """True when the index on disk no longer matches the memory directory -- WITHOUT rewriting it.

    The close needs to ask this rather than regenerate. `[V]` 2026-09-03: the first version
    regenerated at close time, AFTER the content pin had already checked every path -- so the one
    file guaranteed to differ from what the census read was the one the close itself rewrote, in
    direct contradiction of the invariant two hundred lines above it ("EVERY path ANY of the three
    commits carries must hold the bytes the census read"). Harmless only because the index carries
    the doc-scope marker and yields no rows; the moment it yielded one, that row would be committed
    unverdicted. The index is a doc like any other now: the CENSUS refreshes it, the close checks it."""
    path = os.path.join(env.memory, INDEX_NAME)
    return read_text(path) != render(entries(env, rs))


# --------------------------------------------------------------- the pointers the two index files make
_MD_LINK = re.compile(r"\]\(([A-Za-z0-9_./-]+\.md)\)")
_MEM_GLOB = re.compile(r"`(memory/[A-Za-z0-9_*\[\].+-]+)`")
_REPO_PATH = re.compile(r"`((?:docs|src|tools|research|reference|include)/[A-Za-z0-9_/.-]+)`")


def dead_refs(env, rs=None):
    """Pointers in MEMORY.md and CLAUDE.md that resolve to NOTHING -> [(file, kind, pointer)].

    These two files are the reading order itself: MEMORY.md is loaded into every session and
    CLAUDE.md's section 0 is the first thing a reset session opens. A dead pointer in either is a
    next-session dead end, and nothing gated them -- `lessons_gate` fixes its LEDGER to
    `docs/LESSONS.md` and never looks at either."""
    import glob as _glob
    import lessons_gate as _LG
    rs = rs if rs is not None else SC.read_set(env)
    out = []
    mem = read_text(os.path.join(env.memory, "MEMORY.md")) or ""
    cl = read_text(os.path.join(env.repo, "CLAUDE.md")) or ""
    # `[[wikilink]]` is the DOMINANT pointer form in both index files -- 68 distinct in MEMORY.md and
    # 15 in CLAUDE.md, measured 2026-09-03 -- and nothing looked at either: `check_wikilinks` is handed
    # `docs/LESSONS.md` alone (status_census.ratchet_values), which is what `wikilinks-dead` ratchets.
    # All 83 resolve today, so the column read 0 truthfully -- but by luck, not by construction: if one
    # died tomorrow nothing would have moved (DIFF pass, round 1 Q2). A gate that cannot go non-zero
    # for the commonest shape in the file it guards is not guarding that file.
    for who, text in (("MEMORY.md", mem), ("CLAUDE.md", cl)):
        for name in sorted(set(_LG.check_wikilinks(text, env.memory) or [])):
            out.append((who, "wikilink", "[[{}]]".format(name)))
    for p in _MD_LINK.findall(mem):
        if not os.path.isfile(os.path.join(env.memory, os.path.basename(p))):
            out.append(("MEMORY.md", "link", p))
    for g in sorted(set(_MEM_GLOB.findall(mem))):
        if not _glob.glob(os.path.join(env.memory, g[len("memory/"):])):
            out.append(("MEMORY.md", "glob", g))
    for p in sorted(set(_REPO_PATH.findall(cl))):
        if "..." in p:
            continue                       # `src/votv-coop/.../coop/` is prose, not a pointer
        full = os.path.join(env.repo, p)
        # A DIRECTORY is a resolved pointer: `docs/events/` and `reference/mtasa-blue/` are how the
        # reading order names a whole subtree, and an isfile test alone calls all ten of them dead.
        if os.path.isfile(full) or os.path.isdir(full):
            continue
        if os.path.isfile(os.path.join(env.repo, "src", "votv-coop", p)):
            continue                       # the source tree is named from ITS root, not the repo's
        if _glob.glob(full + "*"):
            continue                       # `docs/piles/10` names `10-*.md`
        out.append(("CLAUDE.md", "path", p))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split(NL + NL)[0])
    ap.add_argument("--repo")
    ap.add_argument("--memory-dir")
    ap.add_argument("--history-dir")
    ap.add_argument("--check", action="store_true", help="report dead pointers and exit non-zero on any")
    args = ap.parse_args(argv)
    env = SC.Env(args.repo, args.memory_dir, args.history_dir)
    rs = SC.read_set(env)
    dead = dead_refs(env, rs)
    for f, kind, p in dead:
        print("DEAD  {:<10} {:<5} {}".format(f, kind, p))
    if args.check:
        print("memory_index --check: {} dead pointer(s)".format(len(dead)))
        return 1 if dead else 0
    path, changed = write(env, rs)
    print("{} {} ({} entries, {} dead pointer(s))".format(
        "wrote" if changed else "unchanged", path, len(entries(env, rs)), len(dead)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
